### ISSUE TITLE
Migration TODO

### ISSUE THREAD

**Issue by vvatelot** [cnumr/ecoindex_python_fullstack#2]
- [x] Template PR and issues
- [x] Testing
- [x] Refactoring API dependencies (sort...)
- [x] BFF methods
- [x] script update swagger
- [x] auto update version api
- [x] Record DB
- [x] Health
- [x] Refactor routers dependencies (pagination, host, date)
- [x] Finish migration pydantic v2
- [x] Migrate List to list...
- [x] Readme badges
- [x] Main readme / disclaimer
- [x] Sentry / Glitchtip
- [x] Github actions
  - [x] Build publish docker API (workflow dispatch)
  - [x] Build publish docker CLI (workflow dispatch)
  - [x] Build publish ecoindex compute package
  - [x] Build publish ecoindex scraper package
- [x] Tests
- [x] Start-dev: auto reload

# Commands

### Build docker image

```bash
cd projects/ecoindex_cli
poetry lock
poetry build-project
docker build -t ecoindex-cli:playwright --build-arg="wheel=ecoindex_cli-2.23.0-py3-none-any.whl" .
```

### Build docker image

```bash
cd projects/ecoindex_api
poetry lock
poetry build-project
docker build -t ecoindex-api-backend --build-arg="ecoindex_api-3.1.0-py3-none-any.whl" -f docker/backend/dockerfile .
docker build -t ecoindex-api-worker --build-arg="ecoindex_api-3.1.0-py3-none-any.whl" -f docker/worker/dockerfile .
docker compose up
```

### Create migration

```bash
cd projects/ecoindex_api
poetry run alembic revision --autogenerate -m "Migration name"
```

# Github actions

## Pull request

- Check conventional commit
- Add labels
- Check quality
  - Linting: ruff, mypy
  - Tests
  - Coverage

## Build deploy compute

- Trigger on workflow_dispatch with inputs:
  - `bump_type`: major, minor, patch
- Actions:
  - Checkout
  - Setup python
  - Setup poetry:
    - `pip install poetry`
    - `poetry config virtualenvs.create false`
  - Setup poetry multi project:
    - `poetry self add poetry-multiproject-plugin`
  - Get previous version:
    - `echo "previous_version=$(poetry version)" >> $GITHUB_OUTPUT`
  - Bump version
  - Bump `ecoindex_compute_version` in `components/ecoindex/data/__init__.py`
  - Commit + Push changes:
    - `poetry version ${{ inputs.bump_type }}`
    - `echo "new_version=$(poetry version)" >> $GITHUB_OUTPUT`
    - `chore(compute): bump version to ${version}`
  - Build project:
    - `poetry build-project`
  - [Publish to pypi](https://github.com/marketplace/actions/pypi-publish):
  - [Create tag](https://github.com/marketplace/actions/create-update-tag):
    - `v${version}-compute`
    - target: `${{ github.ref }}`
    - force: true
  - Create changelog:
    - Exclude scopes: api, cli, scraper
    - From: `v${version}-compute`
    - To: `v${previous_version}-compute`
  - Create release:
    - Body: changelog
    - Title: `[compute] ${version}`
